### ISSUE TITLE
[Administrators] Set choices of users manually

### ISSUE THREAD

**Issue by mohe2015** [mohe2015/projektwahl#7]

**Comment by mohe2015** [comment]
We will base it onto the election code -> like a sudo to user

**Comment by Jacar01** [comment]
Thought about another variable (inProject) for user, that can be changed manually but is on 0 if there was no election. -> Admin can see all that have not voted in 1 project

**Comment by mohe2015** [comment]
@Jacar01 I think wie should create that variable but instead provide a function which check that based on all students in all project. Because otherwise there mazly be synchronisation issues if it is true but the student is not actually in a project.

**Comment by mohe2015** [comment]
We may discuss it on discord some time
